Repository itsallcode/white-rabbit, pull requests merged in 2021-07, with the labels that each got.

#202 #177: Add buttons for selecting the previous/next month
  CHANGELOG.md
  README.md
  jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/JavaFxApp.java
  jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/ui/AppUi.java
  jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/JavaFxAppUiTest.java
  jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/ApplicationHelper.java
  logic/src/main/java/org/itsallcode/whiterabbit/logic/storage/MonthIndexStorage.java
Labels: enhancement

#203 #148: Bugfix: add activity to empty day
  CHANGELOG.md
  jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/table/activities/ActivitiesTable.java
  jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/ui/AppUi.java
  logic/src/main/java/org/itsallcode/whiterabbit/logic/model/DayRecord.java
  logic/src/test/java/org/itsallcode/whiterabbit/logic/model/DayRecordTest.java
Labels: bug

#204 #188 Validate projects.json at startup
  CHANGELOG.md
  build.gradle
  jfxui/build.gradle
  jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/uistate/UiStateService.java
  jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/uistate/model/ColumnStateModel.java
  jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/uistate/model/SplitPaneStateModel.java
  jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/uistate/model/StageStateModel.java
  jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/uistate/model/TableStateModel.java
  jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/uistate/model/TitledPaneStateModel.java
  jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/uistate/model/UiStateModel.java
  jfxui/src/test/java/org/itsallcode/whiterabbit/jfxui/uistate/UiStateServiceTest.java
  jfxui/src/test/java/org/itsallcode/whiterabbit/jfxui/uistate/model/UiStateModelTest.java
  jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/JavaFxAppUiTestBase.java
  logic/build.gradle
  logic/src/main/java/org/itsallcode/whiterabbit/logic/ConfigLoader.java
  logic/src/main/java/org/itsallcode/whiterabbit/logic/autocomplete/AutocompleteService.java
  logic/src/main/java/org/itsallcode/whiterabbit/logic/model/json/FieldAccessStrategy.java
  logic/src/main/java/org/itsallcode/whiterabbit/logic/service/AppService.java
  logic/src/main/java/org/itsallcode/whiterabbit/logic/service/project/ProjectConfig.java
  logic/src/main/java/org/itsallcode/whiterabbit/logic/service/project/ProjectImpl.java
  logic/src/main/java/org/itsallcode/whiterabbit/logic/service/project/ProjectService.java
  logic/src/main/java/org/itsallcode/whiterabbit/logic/storage/data/JsonActivity.java
  logic/src/main/java/org/itsallcode/whiterabbit/logic/storage/data/JsonDay.java
  logic/src/main/java/org/itsallcode/whiterabbit/logic/storage/data/JsonFileStorage.java
  logic/src/main/java/org/itsallcode/whiterabbit/logic/storage/data/JsonMonth.java
  logic/src/main/java/org/itsallcode/whiterabbit/logic/storage/data/JsonbFactory.java
  logic/src/test/java/org/itsallcode/whiterabbit/logic/ConfigLoaderTest.java
  logic/src/test/java/org/itsallcode/whiterabbit/logic/service/project/ProjectServiceTest.java
  logic/src/test/java/org/itsallcode/whiterabbit/logic/storage/data/JsonFileStorageTest.java
  plugins/pmsmart/build.gradle
  plugins/pmsmart/src/test/java/org/itsallcode/whiterabbit/plugin/pmsmart/integration/Tester.java
Labels: feature

#205 Added version to archive filename
  README.md
Labels: bug
